ethtool: Fix declaration after label compilation error
Wrap case blocks in braces to allow variable declarations after case
labels, fixing C89 compilation errors:

  am65-cpsw-nuss.c: In function 'cpsw_dump_ale':
  am65-cpsw-nuss.c:423:4: error: a label can only be part of a statement and a declaration is not a statement
      u32 oui_entry = cpsw_ale_get_oui_addr(ale_pos);
      ^~~
  am65-cpsw-nuss.c:432:4: error: a label can only be part of a statement and a declaration is not a statement
      u32 vlan_entry_type = cpsw_ale_get_vlan_entry_type(ale_pos);
      ^~~

Fixes: eb91e05c98d4 ("pretty: Add support for TI K3 CPSW registers and ALE table dump")
Reviewed-by: Carolina Jubran <cjubran@nvidia.com>
Signed-off-by: Gal Pressman <gal@nvidia.com>