ethtool.spec: Add AppStream metainfo file to %files section
The cited commit added the metainfo file and configured it to be
installed via Makefile.am, but forgot to update ethtool.spec.in.
This causes RPM builds to fail with:

  error: Installed (but unpackaged) file(s) found:
     /usr/share/metainfo/org.kernel.software.network.ethtool.metainfo.xml

Add the missing file to the %files section.

Fixes: 02d505bba6fe ("Add AppStream metainfo XML with modalias documented supported hardware.")
Reviewed-by: Tariq Toukan <tariqt@nvidia.com>
Signed-off-by: Gal Pressman <gal@nvidia.com>